services:
#------------------------------------

  postgres:
    image: postgres
    container_name: postgres1
    environment:
      POSTGRES_PASSWORD: bee228
    ports:
      - 4032:5432
    volumes:
      - postgres:/var/lib/postgresql/data

#------------------------------------

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 4000:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

#------------------------------------


  app:
    build: .
    container_name: app-container
    ports:
      - 8080:8080
    depends_on:
      - postgres

#------------------------------------

volumes:
  postgres:
  pgadmin:
  app-container: